### ISSUE TITLE
Getting an error with this script all of a sudden. I think its something simple.

### ISSUE THREAD

**Issue by eurabilis** [pantuts/asskick#3]
Download >> [kat.cr]into.the.grizzly.maze.2015.720p.brrip.x264.yify.torrent

Invalid URL u'//torcache.net/torrent/8FDA5407ABA998957944685CB41CD6B66694E86A.torrent?title=[kat.cr]into.the.grizzly.maze.2015.720p.brrip.x264.yify': No schema supplied. Perhaps you meant http:////torcache.net/torrent/8FDA5407ABA998957944685CB41CD6B66694E86A.torrent?title=[kat.cr]into.the.grizzly.maze.2015.720p.brrip.x264.yify?

**Comment by pantuts** [comment]
please comment here #2

**Comment by pantuts** [comment]
https://github.com/pantuts/asskick/commit/5c0dd98171935e806975b30773dba917a8caab4f
