### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by chiragh241** [pantuts/asskick#6]
Getting the following error: 

HTTPSConnectionPool(host='kickass.to', port=443): Max retries exceeded with url: /usearch/madam%20secretary/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10ca96890>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by pantuts** [comment]
Can you retry? Can't replicate this issue.
